server:
  port: 8088
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
mybatis:
  #  type-aliases-package: com.huhst.dto
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.lw: debug